### ISSUE TITLE
adding Power support

### ISSUE THREAD

**Issue by kdschlosser** [kdschlosser/samsungctl#26]
**THIS IS ONLY GOING TO WORK ON 2014+ TV's**
 am adding power status as well as powering on the TV.

If someone that is running either OSX or Linux can run the attached file for me that would be helpful.
You will need to uncompress the attachment first

Power on your TV and wait until it is connected to your network
Run the following command

    python wake_on_lan.py

It will ask you to input the IP address. enter the IP of your TV. (then press enter)
It will then print out the MAC address of he TV if it find it.

**READ NEXT STEPS AND DO IN ORDER**
Power your TV off if it prints out the MAC address
You will then be asked if you want to send a WOL packet. After your TV has been powered off (standby) for at least a minute. key in Y and press enter.

see if the TV turns on.

[wake_on_lan.zip](https://github.com/kdschlosser/samsungctl/files/2742842/wake_on_lan.zip)

**Comment by raydog153** [comment]
Holy smoke...it works!!!! This is only thing I can get to work on my UN40H5203 TV. In fact I have a 2008 LN52A750 samsung and I can turn it on using iOS Roku remote, but not the UN40H5203 TV.

Wasn't sure if I needed to leave the app running or not, so I did and it didn't work so I ran the app again and it worked and TV started up! How to shut it off thou? lol

**Comment by kdschlosser** [comment]
turning off the TV is easy to do. the turning it on was the hard part. so I now know this works properly. I will merge the code that adds power on functionality.

**Comment by kdschlosser** [comment]
I will get the code all done up for the H and J series TV soon enough.
