### ISSUE TITLE
token issue with more than one tv

### ISSUE THREAD

**Issue by dominch** [kdschlosser/samsungctl#3]
Hello 
There is a problem with token.txt file, 
With this code You can control only one tv at once, when trying to control another TV token needs to be changed and You need to allow that remote on TV again. 
Fix for this is simple, I just added string from --id into filename and started to use that switch, now I can easily control more tvs just using different token files.

**Comment by kdschlosser** [comment]
I am aware of the issues with the token file. and the fact that it only allows for storage of a single token. 
There is a test solution that fixes issues like this one located here https://github.com/kdschlosser/samsungctl/issues/2#issuecomment-441993696

there have been some reported issues with linux and osx if you are running one of the 2 the problem may not occur. it would be nice to know if that is the case. if running on windows it works without issue. it is a test version so there is bound to be bugs. I added 3000+ lines of code so problems will arise and I will get them sorted.

**Comment by kdschlosser** [comment]
this problem has been fixed and it is now available in the master branch
