### ISSUE TITLE
Added power  on to the library

### ISSUE THREAD

**Issue by kdschlosser** [kdschlosser/samsungctl#30]
if anyone wants to give it a go I added power on as well as better handling for power off. this can be done from the command line using the keys

KEY_POWERON
KEY_POWEROFF

and if you want to toggle the power

KEY_POWER

**Comment by vitalets** [comment]
@kdschlosser how technically `KEY_POWERON` works? As I understand when TV is off there is no websocket connection and library can't send `KEY_POWERON` command..

**Comment by kdschlosser** [comment]
no it cannot send a command through the websocket when the TV  is off. I am sending a Wake On LAN (WOL) packet to the TV which "wakes" (turns on) the TV.

**Comment by arsaboo** [comment]
Does it also report the current state, i.e., whether the TV is on/off.

**Comment by raydog153** [comment]
Not all TVs support WOL. One other feature I found out on my TV is that in the Service Menu there is a setting to restore last powered state of TV (commonly used for restoring TV to last known state after power outage....or smart switch). Thou I rather not use smart switch since it adds yet another device.

**Comment by arsaboo** [comment]
Getting `ImportError: cannot import name 'wake_on_lan'`

**Comment by arsaboo** [comment]
So, I tried this and WOL is not working for me. 

```
pi@raspberrypi:~/samsungctl $ samsungctl --host 192.168.2.252 --method websocket --port 8002 --name remoteCmd KEY_POWER
Unable to power off the TV
```

I also tried it in Home Assistant where the component was working for me before the WOL changes and I get the following error: 
```bash
Log Details (ERROR)
Thu Jan 10 2019 10:58:08 GMT-0500 (Eastern Standard Time)

Error while setting up platform samsungtv
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/media_player/samsungtv.py", line 81, in setup_platform
    add_entities([SamsungTVDevice(host, port, name, timeout, mac)])
  File "/home/homeassistant/.homeassistant/custom_components/media_player/samsungtv.py", line 92, in __init__
    import custom_components.samsungctl as samsungctl
  File "/home/homeassistant/.homeassistant/custom_components/samsungctl/__init__.py", line 24, in <module>
    from .remote import Remote # NOQA
  File "/home/homeassistant/.homeassistant/custom_components/samsungctl/remote.py", line 5, in <module>
    from .remote_websocket import RemoteWebsocket
  File "/home/homeassistant/.homeassistant/custom_components/samsungctl/remote_websocket.py", line 15, in <module>
    from . import wake_on_lan
ImportError: cannot import name 'wake_on_lan'
```

**Comment by jnimmo** [comment]
@arsaboo the HA stuff should be discussed on a new issue on HA’s Github. I’m on leave next week so planning to work on the HA side then, so will drop a link for any discussion then unless someone else beats me to it

**Comment by arsaboo** [comment]
@jnimmo I have removed the HA logs, but the WOL does not work even out side HA.

**Comment by AidasK** [comment]
Power on/off works on UE75NU7172 samsung model. But poweron command has some strange behavior. It sometimes need to be sent twice. First call turns on the Samsung TV API, it is working, I am able to send all other commands, but TV screen is black. As it was in sleeping mode. On the second time, TV turns on.

**Comment by Mark-Sellwood** [comment]
Hi @arsaboo How did you install this?
I did a `git clone https://github.com/kdschlosser/samsungctl`
Then `python setup.py install`
This gives the following error: -
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import setuptools # NOQA
ImportError: No module named setuptools

So I tried: -
pi@SPARE-PI:~/domoticz/plugins/samsungctl $ sudo pip3 install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages
pi@SPARE-PI:~/domoticz/plugins/samsungctl $

Am I missing something?
