### ISSUE TITLE
intergrating the UPNP side of the TV

### ISSUE THREAD

**Issue by kdschlosser** [kdschlosser/samsungctl#39]
I still want to tackle the UPNP side of the TV. adding this to samsungctl will make it able to detect the TV as well as determine the connection type to be used. It is going to expand the functionality for the older models greatly as well. plus add some nice features for the newer ones like direct volume input. and direct mute control. we can also get some notifications using UPNP as well.

I have most of thee coding done up for the UPNP there were some issues with the detection portion of it.
if there is anyone willing to assist me in some trial and error that would be very helpful. I am going to be really focusing on proper SSDP packet broadcasts and responses.

anyone willing to help drop a line.

**Comment by dcorsus** [comment]
don't know Python unless I can figure out how to run in Visual Studio.
But ask away on SSDP/UPNP questions

**Comment by kdschlosser** [comment]
I basically need someone that knows how to run the code and to report what is or is not working in it's entirety. 

I need someone that knows how to program in any language it doesn't matter. that person is going to have a much better understanding and understand the vocabulary.

Python is a high level programming language and is extremely easy to learn. it is even more so for someone that has knowledge of other languages.

You mention Visual Studio so I am going to guess that you have some kind of knowledge of C, C++ or C\# if that is the case then python will be a breeze for you to pick up on. I already have a whole UPNP deal written up for samsungctl. There may be an issue with the detection portion of it. that is what I need to hammer out. I have a feeling I know what it is and I will make some modifications to the code to see if the problem is what I think it is.

here is a link to the repo that has all of the UPNP stuff. 

https://github.com/kdschlosser/UPNP_Device

clone the master branch and run

    python setup.py install

I will add an example code snippit to the readme file that will show how to use it.

**Comment by jnimmo** [comment]
I’ll try and have a look tomorrow

**Comment by kdschlosser** [comment]
@dcorsus 
BTW. I do not have any questions about SSDP or UPNP. it's just that it seems there is no standard as to how devices respond to SSDP discovery packets. some will respond to a broadcast. other will respond only by a direct query. while other are a combination of both. 

So I am trying to nail down the most efficient mechanism that will do both. I want this to be as fast as possible.


It also appears that there is no standard on if a devicee should pat attetion to what the value of MX is which is the TTL (Time To Live) for the discovery process. because devices will respond whenever it is they feel like it not caring what the MX is set to. and of course Samsung devices are such devices.

**Comment by kdschlosser** [comment]
I added a console script to it.

if you have the python scripts path in your environments path then all you need to run as a command is

    upnp_device -vvvv > discover_output.txt

if you want to expressly target your TV

    upnp_device -vvvv 192.168.1.1 > discover_output.txt

**Comment by dcorsus** [comment]
Actually ALL device respond to a broadcast or they don't have it implemented properly. Don't think I've run into a device that does not respond to a broadcast but have run into plenty devices that don't have proper service xml, especially those devices that use UPNP for the sole purpose of being discovered (example DIAL devices). I've set MX to 4 but never really paid attention to it, as I said, broadcast discovery works well BUT wireless networks tend to be challenged on occasion by broadcasts, especially more recent mimo networks. I do wait 30 seconds for all responses to come in.
Makes sure you send out an ssdp:discovery for the root device (ST: upnp:rootdevice) and devices are supposed to respond for each device they have. I do listen to the selected physical Ethernet ports but also to the loopback port (127.0.0.1). The last seems to be very needed when you run on Linux.

**Comment by dcorsus** [comment]
Did I forget to mention that Samsung's UPNP implementation has always been top-notch, including sending ssdp:bye-bye which many other devices don't do. Only challenge I experienced (I think with my c-model) is that the TV was a little to quick to send ssdp:alive when turned on, and a subsequent get to the device XML sometimes failed, so I built in a small delay

**Comment by jnimmo** [comment]
Running into an issue when not targeting a specific TV (log in the discover_output_all.txt)- but command completes when targeting a TV. I think the issue may be caused by a legacy mode Samsung as get the error if I target it's IP but all the newer ones work
[discover_output_targetted.txt](https://github.com/kdschlosser/samsungctl/files/2753535/discover_output_targetted.txt)
[discover_output_all.txt](https://github.com/kdschlosser/samsungctl/files/2753536/discover_output_all.txt)

**Comment by kdschlosser** [comment]
top notch eeh??? Not even close.. I really do hope you were being sarcastic LOL

some Linksys routers will only respond to a direct query and not a broadcast. for instance the LRT224, this is the model of the router I have and it doees not make a peep when you send a broadcasted discovery packet.  it does send out the alive packets every 5 minutes. but that sucks if you wanted to programmatically set a port forward on the router. On Windows I wrote a program that will grab the gateways (and and other information) without the need to use subprocess to call another program and parse the output. On NIX os's I have not been able to locate a way to get that information without using subprocess (or the like). I think that starting another program and parsing it's output is kind of a hack way to go about getting information from the OS.

I have come across some Samsung TV's that will report UPNP classes that they do not send in a broadcast.

The discovery process I write enumerates all of the IP's on all of the NIC's for Windows, Linux and Darwin.
I have the script bind to each and every IP and then send a broadcast.
it does a really good job. I can grab all of the UPNP data off of a network in roughly 5 seconds.

what I have it do is I set up a thread for each IP address that the host machine has. it send s out the broadcast and as each device (unique IP) reports back i then start a thread that sends out a direct query to that IP.

**Comment by kdschlosser** [comment]
@jnimmo 

it is throwing an error because of a device not having a proper UPNP implementation
I fixed the develop branch to allow the program to continue to run when that happens.

so if you want to give it a shot again that would be most helpful.

**Comment by jnimmo** [comment]
[discover_output.txt](https://github.com/kdschlosser/samsungctl/files/2753562/discover_output.txt)
Perfect that looks to give more useful error messages

**Comment by kdschlosser** [comment]
do me another favor...  increase the timeout..

    --timeout 15

**Comment by kdschlosser** [comment]
I am a little bit confused by the output.

in your first attachment there is this TV

UA50MU6100
IP Address: 192.168.2.40

and it is not in thee latest attachment.



how many samsung TV's do you have???

**Comment by jnimmo** [comment]
Sorry I had that one turned off the second time around -  there are 5 TVs, one legacy and four running the 1250 firmware
Here is the 15 second output with all turned on
[discover_output_15s.txt](https://github.com/kdschlosser/samsungctl/files/2753618/discover_output_15s.txt)

**Comment by kdschlosser** [comment]
thanks

**Comment by kdschlosser** [comment]
I added in the UPNP portions.

You can give it a test by cloning this branch.

 https://github.com/kdschlosser/samsungctl/tree/adding_in_upnp

here is a test script

```python
import samsungctl

config = samsungctl.Config(
    name='samsungctl',
    method='websocket',
    port=8002,
)

remote = samsungctl.Remote(config)
remote.connect_upnp()

print(remote.upnp_tv.as_dict)
```

**Comment by kdschlosser** [comment]
as far as that UPNP_Device library goes. I added a dump feature to it. 

    upnp_devicee --dump "directory/to/dump/files"

this is going to make an exact replica of the file/folder structure thee eevice has for the paths and filenames to the UPNP XML files. it is also going to output the contents of the XML files.

If I get willing participants to zip up that folder and attach it to a comment in here that is going to help me out a lot.

I also discovered a couple of glitches in the original code. So those are fixed now as well.

**Comment by matthieut59** [comment]
I ll also have a try, is upnp also a way to get the currently playing media ? For instance I have a Frame Samsung TV (43LS model) from 2018, and the only I have today to know if it s playing a media or in "art mode" is by checking current consumption...

**Comment by kdschlosser** [comment]
I know nothing about the frame TV's so your guess is a good as mine as far as what is going to work or not.

I believe the Frame TV's have something called "slideshow mode" and there is a UPNP concession for this.

If you join us over in my UPNP_Device repo we are testing that side of the functionality. once that is nailed down I am going to add those bits into samsungctl.
