### ISSUE TITLE
Error during setupy.py install

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#49]
Hello,

used to work before last commit, but now I got on Windows 10 (at the end of install): 

Processing samsungctl-0.8.0b0-py3.7.egg
removing 'c:\users\mtourlouse\appdata\local\programs\python\python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg' (and everything under it)
creating c:\users\mtourlouse\appdata\local\programs\python\python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg
Extracting samsungctl-0.8.0b0-py3.7.egg to c:\users\mtourlouse\appdata\local\programs\python\python37-32\lib\site-packages
samsungctl 0.8.0b0 is already the active version in easy-install.pth
Installing samsungctl-script.py script to C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Scripts
Installing samsungctl.exe script to C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Scripts
Installing samsungctl.exe.manifest script to C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Scripts

Installed c:\users\mtourlouse\appdata\local\programs\python\python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg
Processing dependencies for samsungctl==0.8.0b0
Searching for pycrypto
Reading https://pypi.python.org/simple/pycrypto/
Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz#sha256=f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c
Best match: pycrypto 2.6.1
Processing pycrypto-2.6.1.tar.gz
Writing C:\Users\MTOURL~1\AppData\Local\Temp\easy_install-vk0vyerw\pycrypto-2.6.1\setup.cfg
Running pycrypto-2.6.1\setup.py -q bdist_egg --dist-dir C:\Users\MTOURL~1\AppData\Local\Temp\easy_install-vk0vyerw\pycrypto-2.6.1\egg-dist-tmp-oxs8ra9m
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
winrand.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(27): error C2061: syntax error: identifier 'intmax_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(28): error C2061: syntax error: identifier 'rem'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(28): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(29): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(31): error C2061: syntax error: identifier 'imaxdiv_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(31): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(41): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(42): error C2146: syntax error: missing ')' before identifier '_Number'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(42): error C2061: syntax error: identifier '_Number'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(42): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(43): error C2059: syntax error: ')'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(46): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(47): error C2146: syntax error: missing ')' before identifier '_Numerator'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(47): error C2061: syntax error: identifier '_Numerator'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(47): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(47): error C2059: syntax error: ','
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(49): error C2059: syntax error: ')'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(51): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(57): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(64): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(70): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(77): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(83): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(90): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(96): error C2143: syntax error: missing '{' before '__cdecl'
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

Can you have a look ?

Thks,

matt

**Comment by matthieut59** [comment]
Issue seems to be coming from pycrypto lib not supported on windows : 
https://github.com/dlitz/pycrypto/issues/238

As advised should switch to another crypto lib if possible ?

**Comment by kdschlosser** [comment]
it is supported on windows. and it is running just fine. You have a development environment that is set up that is bumping heads with the compiling process of pycrypto

**Comment by kdschlosser** [comment]
```
running install
running bdist_egg
running egg_info
writing requirements to samsungctl.egg-info\requires.txt
writing samsungctl.egg-info\PKG-INFO
writing dependency_links to samsungctl.egg-info\dependency_links.txt
writing entry points to samsungctl.egg-info\entry_points.txt
writing top-level names to samsungctl.egg-info\top_level.txt
reading manifest file 'samsungctl.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
writing manifest file 'samsungctl.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying samsungctl\application.py -> build\lib\samsungctl
copying samsungctl\config.py -> build\lib\samsungctl
copying samsungctl\exceptions.py -> build\lib\samsungctl
copying samsungctl\key_mappings.py -> build\lib\samsungctl
copying samsungctl\remote.py -> build\lib\samsungctl
copying samsungctl\remote_legacy.py -> build\lib\samsungctl
copying samsungctl\remote_websocket.py -> build\lib\samsungctl
copying samsungctl\utils.py -> build\lib\samsungctl
copying samsungctl\wake_on_lan.py -> build\lib\samsungctl
copying samsungctl\__init__.py -> build\lib\samsungctl
copying samsungctl\__main__.py -> build\lib\samsungctl
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\application.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\config.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\exceptions.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\interactive.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\key_mappings.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\remote.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\remote_encrypted.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\remote_legacy.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\remote_websocket.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\utils.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\wake_on_lan.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\__init__.py -> build\bdist.win-amd64\egg\samsungctl
copying build\lib\samsungctl\__main__.py -> build\bdist.win-amd64\egg\samsungctl
byte-compiling build\bdist.win-amd64\egg\samsungctl\application.py to application.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\config.py to config.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\exceptions.py to exceptions.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\interactive.py to interactive.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\key_mappings.py to key_mappings.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\remote.py to remote.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\remote_encrypted.py to remote_encrypted.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\remote_legacy.py to remote_legacy.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\remote_websocket.py to remote_websocket.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\utils.py to utils.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\wake_on_lan.py to wake_on_lan.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\__init__.py to __init__.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\samsungctl\__main__.py to __main__.cpython-35.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying samsungctl.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\samsungctl-0.8.0b0-py3.5.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing samsungctl-0.8.0b0-py3.5.egg
creating c:\stackless35\lib\site-packages\samsungctl-0.8.0b0-py3.5.egg
Extracting samsungctl-0.8.0b0-py3.5.egg to c:\stackless35\lib\site-packages
Removing samsungctl 0.7.1+1 from easy-install.pth file
Adding samsungctl 0.8.0b0 to easy-install.pth file
Installing samsungctl-script.py script to c:\stackless35\Scripts
Installing samsungctl.exe script to c:\stackless35\Scripts

Installed c:\stackless35\lib\site-packages\samsungctl-0.8.0b0-py3.5.egg
Processing dependencies for samsungctl==0.8.0b0
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
Adding pycrypto 2.6.1 to easy-install.pth file

Using c:\stackless35\lib\site-packages
Searching for requests==2.19.1
Best match: requests 2.19.1
Adding requests 2.19.1 to easy-install.pth file

Using c:\stackless35\lib\site-packages
Searching for websocket-client==0.54.0
Best match: websocket-client 0.54.0
Processing websocket_client-0.54.0-py3.5.egg
websocket-client 0.54.0 is already the active version in easy-install.pth
Installing wsdump.py script to c:\stackless35\Scripts

Using c:\stackless35\lib\site-packages\websocket_client-0.54.0-py3.5.egg
Searching for certifi==2018.8.24
Best match: certifi 2018.8.24
Adding certifi 2018.8.24 to easy-install.pth file

Using c:\stackless35\lib\site-packages
Searching for urllib3==1.23
Best match: urllib3 1.23
Adding urllib3 1.23 to easy-install.pth file

Using c:\stackless35\lib\site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect-script.py script to c:\stackless35\Scripts
Installing chardetect.exe script to c:\stackless35\Scripts

Using c:\stackless35\lib\site-packages
Searching for idna==2.7
Best match: idna 2.7
Adding idna 2.7 to easy-install.pth file

Using c:\stackless35\lib\site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using c:\stackless35\lib\site-packages
Finished processing dependencies for samsungctl==0.8.0b0
```

**Comment by kdschlosser** [comment]
I found the problem. It's the Windows 10 SDK and pycrypto. so I have changed out pycrypto for pycryptodome.

**Comment by matthieut59** [comment]
Thks for your quick answer! I ll try it as soon as released :)

**Comment by kdschlosser** [comment]
the changes have already been added to the master branch

**Comment by matthieut59** [comment]
Working, thanks for the reactivity!

**Comment by kdschlosser** [comment]
no worries m8. Glad it is up and running for ya.
