### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'quiet'

### ISSUE THREAD

**Issue by mikelitka** [kdschlosser/samsungctl#50]
Any ideas on this error?

[root@homeassistant bin]# ./samsungctl --version
samsungctl 0.8.0b
[root@homeassistant bin]# ./samsungctl --host 10.99.1.173 --method websockets --port 8002 KEY_VOLUP
Traceback (most recent call last):
  File "./samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/common/apps/homeassistant/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__main__.py", line 247, in main
    config = Config(**config)
TypeError: __init__() got an unexpected keyword argument 'quiet'

Running this on a host that also has homeassistant installed.

**Comment by kdschlosser** [comment]
this issue should be resolved

**Comment by mikelitka** [comment]
Yep. Pulled again and there was an update. Appreciate the quick response.
