### ISSUE TITLE
Token not getting written

### ISSUE THREAD

**Issue by mikelitka** [kdschlosser/samsungctl#51]
I am running the following command as root:

./samsungctl -i -vvv --host 10.99.1.214 --method websocket --port 8002 KEY_VOLUP

Each time I run it I am prompted by the TV to allow the device. For some reason the token isn't being written down to the file system at ~/.samsungctl/token.txt.

Any ideas on additional troubleshooting here?

**Comment by mikelitka** [comment]
If I call out the token file explicitly, accept the prompt, it still doesn't get written out to file system. 

[root@homeassistant bin]# ./samsungctl -vvv --host 10.99.1.214 --method websocket --port 8002 KEY_VOLUP --token ~/.samsungctl/token2.txt
using saved token: /root/.samsungctl/token2.txt
incoming message: {"data":{"clients":[{"attributes":{"name":"c2Ftc3VuZ2N0bA==","token":"/root/.samsungctl/token2.txt"},"connectTime":1548250672236,"deviceName":"c2Ftc3VuZ2N0bA==","id":"ea428712-5e1f-46b2-8e42-2016c3dfdc70","isHost":false}],"id":"ea428712-5e1f-46b2-8e42-2016c3dfdc70","token":"10456855"},"event":"ms.channel.connect"}

new token: 10456855
Access granted.
Sending control command: {'Cmd': 'Click', 'DataOfCmd': 'KEY_VOLUP', 'Option': 'false', 'TypeOfRemote': 'SendRemoteKey'}
Websocket closed
[root@homeassistant bin]# ls -al ~/.samsungctl
total 0
drwxr-xr-x  2 root root   6 Jan 23 08:37 .
dr-xr-x---. 8 root root 288 Jan 21 19:28 ..
[root@homeassistant bin]#

**Comment by matthieut59** [comment]
I have submitted a PR to fix one of the issue (linked to writting file isntead of reading it), but I still get confused with the load operation trying to extract a json format whereas config was stored as a dict.

I ll let owner of the repo touch this one

here : https://github.com/kdschlosser/samsungctl/blob/master/samsungctl/config.py#L123

**Comment by kdschlosser** [comment]
OK so here goes. the original design of the config files is a json object. which is a python dictionary with some slight differences. This can be confusing for python "newbies" and to be honest adds a ton of additional punctuation and syntax related things that can open the door for errors. There is not enough information that is being stored that warrants using a json structure. so I opted to simply use a flat file. with  

```
name = samsungctl
description = some description
host = 192.168.1.1
port = 55000
id = 123456789
method = websocket
timeout = 0
token = some_token_data
device_id = 4984487
upnp_locations = None
```

I have to make some changes to better handle parsing a loaded file But essentially what you will end up with is what you see above.

if you create a config file that looks like this.

```
TV name
Name = samsungctl
DESCRIPTION= some description
host=192.168.1.1
PoRt = 55000
just some random text
id = 123456789

method = websocket
timeout = 0
token = some_token_data
device_id = null


upnp_locations = None
```

It will read the data properly.
the only thing the parser cares about seeing is the equals in the line. this is the marker that the line should be read as a config line.

Nice thing is that if you do have any lines that are not config lines. when you save the config file. it is not going to overwrite those lines.

the parsing of the json is for backwards compatibility with the old config file. once you have loaded and then saved the file the json will be removed and the new flat file will be put into it's place.

Right now I am going to make some changes to how the file gets parsed.

**Comment by mikelitka** [comment]
Just so I am clear, is this token not being written to the file system a configuration file issue? I am using all switches, I wouldn't have thought that the config file would be used with the switches overriding it.

**Comment by kdschlosser** [comment]
OK so i updated the Config parsing.

```
TV name
Name = samsungctl
DESCRIPTION= some description
        host=192.168.1.1
PoRt = 55000
just some random text
id = 123456789
some random key = this is fine
method = websocket
timeout = null
token = some_token_data
device_id = 


upnp_locations = None
```

it will now handle a file that looks like the above.
I don't know why someone's config file would look like this. But one thing I have realized over the 3 years I have been programming is this. DON'T ASK, just make it so that it will handle it.  LOL.

**Comment by kdschlosser** [comment]
You have to save the config file.

did you read the documentation???

**Comment by kdschlosser** [comment]
writing files to the filesystem without the user having knowledge of it taking place (other then a temp file) is not something I am very keen on. hence the reason why i did away with the token.txt file.. the user should be fully aware of what is being written to their disk. and they are the ones that should specifically ask for the data to be written. or loaded for that matter.

**Comment by kdschlosser** [comment]
If you are using the command line to use samsungctl I am going to add a concession to handle the config file loading and saving right now.. I just have not gotten there quite yet. one step at a time.

**Comment by mikelitka** [comment]
I don't need the token switch feature, I just thought they were overrides. I am happy to use the config file if that is the requirement. I did see that in the docs but again thought I could override. Thanks for your hard work here.

**Comment by kdschlosser** [comment]
if you do not specify a config file to save and load from and your TV requires the use of a token. you will have to pair each and every time.

**Comment by mikelitka** [comment]
Getting this error:

[root@homeassistant samsungctl]# /common/apps/homeassistant/bin/samsungctl --method=websocket --host=10.99.1.248 --config-file ~/.config/samsungctl.conf KEY_MENU
Traceback (most recent call last):
  File "/common/apps/homeassistant/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/common/apps/homeassistant/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__main__.py", line 257, in main
    config = Config.load(args.config_file)
  File "/common/apps/homeassistant/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/config.py", line 166, in load
    self = cls.__new__(**config)
TypeError: object.__new__(): not enough arguments
[root@homeassistant samsungctl]#
[root@homeassistant samsungctl]#
[root@homeassistant samsungctl]#
[root@homeassistant samsungctl]# cat ~/.config/samsungctl.conf
TV name
Name = samsungctl
DESCRIPTION= some description
host=10.99.1.248
PoRt = 8002
just some random text
id = 123456789

method = websocket
timeout = 0
token = some_token_data
device_id = null


upnp_locations = None

**Comment by kdschlosser** [comment]
ooops.. heh forgot to add cls to that bugger.

**Comment by kdschlosser** [comment]
ok it should be fixed now.

**Comment by mikelitka** [comment]
Looks like I am getting a different error now:

[root@homeassistant samsungctl]#  /common/apps/homeassistant/bin/samsungctl --method=websocket --host=10.99.1.252 --config-file ~/.config/samsungctl.conf KEY_MENU
Traceback (most recent call last):
  File "/common/apps/homeassistant/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/common/apps/homeassistant/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__main__.py", line 269, in main
    if not config.host:
AttributeError: 'NoneType' object has no attribute 'host'

[root@homeassistant samsungctl]# cat ~/.config/samsungctl.conf
TV name
Name = samsungctl
DESCRIPTION= some description
host=10.99.1.248
PoRt = 8002
just some random text
id = 123456789

method = websocket
timeout = 0
token = some_token_data
device_id = null


upnp_locations = None

**Comment by tya** [comment]
@mikelitka wanna test out my fix for this issue?  https://github.com/kdschlosser/samsungctl/pull/53

**Comment by mikelitka** [comment]
@tya Bango! Nice work that fixed it. Token is now working on repeated calls.  Thanks all for getting this sorted!
