### ISSUE TITLE
An easy one :  No module named 'samsungctl.upnp'

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#57]
Hello,

Stuck at first import of samsungctl lib :)

λ python debugsamsung.py
Traceback (most recent call last):
  File "debugsamsung.py", line 8, in <module>
    import samsungctl
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\__init__.py", line 20, in <module>
    from .remote import Remote # NOQA
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 8, in <module>
    from .upnp import UPNPTV
ModuleNotFoundError: No module named 'samsungctl.upnp'

**Comment by matthieut59** [comment]
I manually copied the upnp folder to the install path it worked, So I guess something is missing in the setup.py part to do this

**Comment by mikelitka** [comment]
Looks like there might be a fat finger:

error: package directory 'samsungctl]/py3rijndael' does not exist

[root@localhost samsungctl]# python3.6 setup.py install
/usr/lib/python3.6/site-packages/setuptools/dist.py:397: UserWarning:
Normalizing '0.8.0b' to '0.8.0b0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing samsungctl.egg-info/PKG-INFO
writing dependency_links to samsungctl.egg-info/dependency_links.txt
writing entry points to samsungctl.egg-info/entry_points.txt
writing requirements to samsungctl.egg-info/requires.txt
writing top-level names to samsungctl.egg-info/top_level.txt
error: package directory 'samsungctl]/py3rijndael' does not exist

**Comment by kdschlosser** [comment]
and there is!.
