### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'join'

### ISSUE THREAD

**Issue by mikelitka** [kdschlosser/samsungctl#61]
Commands are executing correctly, however during the closing of the connection it is throwing an error. This looks to be cosmetic:

[root@localhost ~]# samsungctl --config-file tv-living-room.conf -vvvv KEY_VOLUP
using saved token: 15929070
{"data":{"clients":[{"attributes":{"name":"c2Ftc3VuZ2N0bA==","token":"15929070"},"connectTime":1548528152155,"deviceName":"c2Ftc3VuZ2N0bA==","id":"a7c3482b-d779-43b4-8ab3-d5a33e5bfc3d","isHost":false}],"id":"a7c3482b-d779-43b4-8ab3-d5a33e5bfc3d"},"event":"ms.channel.connect"}

incoming message: {"data":{"clients":[{"attributes":{"name":"c2Ftc3VuZ2N0bA==","token":"15929070"},"connectTime":1548528152155,"deviceName":"c2Ftc3VuZ2N0bA==","id":"a7c3482b-d779-43b4-8ab3-d5a33e5bfc3d","isHost":false}],"id":"a7c3482b-d779-43b4-8ab3-d5a33e5bfc3d"},"event":"ms.channel.connect"}

Access granted.
Access granted.
Sending control command: {'Cmd': 'Click', 'DataOfCmd': 'KEY_VOLUP', 'Option': 'false', 'TypeOfRemote': 'SendRemoteKey'}
Websocket closed
Traceback (most recent call last):
  File "/usr/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__main__.py", line 415, in main
    remote.source = args.source
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 72, in __exit__
    self.close()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_websocket.py", line 272, in close
    self._thread.join(3.0)
AttributeError: 'NoneType' object has no attribute 'join

And related to:

    def close(self):
        """Close the connection."""
        if self.sock is not None:
            self._loop_event.set()
            self.sock.close()
            self._thread.join(3.0)
            if self._thread is not None:
                raise RuntimeError('Loop thread did not properly terminate')

**Comment by matthieut59** [comment]
same here
