### ISSUE TITLE
UPNP_Device discover.py -> no output

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#68]
Hello,

here is my output : 
C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device
λ python discover.py > discover_output.txt
SSDP: 239.255.255.250
M-SEARCH * HTTP/1.1
ST: upnp:rootdevice
MAN: "ssdp:discover"
HOST: 239.255.255.250:1900
MX: 1
Content-Length: 0

SSDP: 239.255.255.250
M-SEARCH * HTTP/1.1
ST: upnp:rootdevice
MAN: "ssdp:discover"
HOST: 239.255.255.250:1900
MX: 1
Content-Length: 0

But I dont have any discover_output.txt :/

Thks,

matt

**Comment by kdschlosser** [comment]
do you have the TV powered on and connected to your network?

**Comment by matthieut59** [comment]
Yes, and I also have some other Upnp device that hould be discovered, except if you filter on samsung TV ?

**Comment by kdschlosser** [comment]
since you are running the discover directly there is no filter in place. it should be working.

**Comment by matthieut59** [comment]
working now
