### ISSUE TITLE
TV asks for authorizarization everytime I try to connect

### ISSUE THREAD

**Issue by d2hf** [kdschlosser/samsungctl#79]
TV keeps asking me for authorization, I am having trouble to understand how to use the token...

```
import samsungctl
from time import sleep

config = samsungctl.Config(
    name= "samsungctl",
    description= "PC",
    host= "172.16.254.158",
    port= 8002,
    method= "websocket",
    timeout= 0)




with samsungctl.Remote(config) as remote:
    print(remote.power)

```

**Comment by kdschlosser** [comment]
ok so you need to use this as a script to run.

You will only have to do this a single time. and then after that you will use the script below this one

replace SAVE_PATH/FILE_NAME with thee path and filename you want to save the config data to.
be sure to do this in both scripts. once the config is saved there is no need to use the first script again unless you delete the pairing in your TV.


```python
import samsungctl
from time import sleep

config = samsungctl.Config(
    name= "samsungctl",
    host= "172.16.254.158",
    method= "websocket"
)

with samsungctl.Remote(config) as remote:
    print(remote.power)

config.save('SAVE_PATH/FILE_NAME')
```

script # 2

```python
import samsungctl
from time import sleep

config = samsungctl.Config.load('SAVE_PATH/FILE_NAME')

with samsungctl.Remote(config) as remote:
    print(remote.power)

config.save()
```

**Comment by matthieut59** [comment]
works for me this way

**Comment by kdschlosser** [comment]
can we close this issue?

**Comment by d2hf** [comment]
yes, it works! thanks.
